// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqgKnwzH8FuuQCmw8oFPwkl_bREO1GRDc',
    appId: '1:419028926058:android:808d4d2d74826708985413',
    messagingSenderId: '419028926058',
    projectId: 'couchcinema-b03e3',
    databaseURL: 'https://couchcinema-b03e3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'couchcinema-b03e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6EGf0gwC8NFXDwPfhtJdvAoemki11Nuw',
    appId: '1:419028926058:ios:14c0564e4d9344d2985413',
    messagingSenderId: '419028926058',
    projectId: 'couchcinema-b03e3',
    databaseURL: 'https://couchcinema-b03e3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'couchcinema-b03e3.appspot.com',
    iosClientId: '419028926058-mh3pf905ncbn6bniaabtoc21nni4m8il.apps.googleusercontent.com',
    iosBundleId: 'com.schweizerle.couchcinema.couch_cinema',
  );
}
